version: "3"

services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=psql
            - POSTGRES_DB=agillee
        ports:
            - "5234:5432"

    agillee:
        build: .
        depends_on:
            - postgres
